config/routes.rb
DesenvolvimentoEnxuto::Application.routes.draw do
  resources :issues

  resources :users

  resources :projects

  resources :organizations

  resources :labels

end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :id_git %><br />
    <%= f.text_field :id_git %>
  </div>
  <div class="field">
    <%= f.label :login_git %><br />
    <%= f.text_field :login_git %>
  </div>
  <div class="field">
    <%= f.label :url_git %><br />
    <%= f.text_field :url_git %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Description</th>
    <th>Id git</th>
    <th>Login git</th>
    <th>Url git</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= organization.url %></td>
    <td><%= organization.description %></td>
    <td><%= organization.id_git %></td>
    <td><%= organization.login_git %></td>
    <td><%= organization.url_git %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Url:</b>
  <%= @organization.url %>
</p>

<p>
  <b>Description:</b>
  <%= @organization.description %>
</p>

<p>
  <b>Id git:</b>
  <%= @organization.id_git %>
</p>

<p>
  <b>Login git:</b>
  <%= @organization.login_git %>
</p>

<p>
  <b>Url git:</b>
  <%= @organization.url_git %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>